theme: jekyll-theme-minimal
title: RS1 CS 422 Fall 2022
description: Implementation of the control condition and experimental condition in R. Krishna, K. Hata, S. Chen, J. Kravitz, D.A. Shamma, L. Fei-Fei, M.S. Bernstein. "Embracing error to enable rapid crowdsourcing." CHI 2016.